apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kafka-cluster.yaml
- kafka-node-pool-broker.yaml
- kafka-node-pool-controller.yaml
- kafka-topic.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: fhir
    managed-by: kustomize
