apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: fhir-controller
  labels:
    strimzi.io/cluster: fhir-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
