apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fhir

resources:
  - kafka-cluster.yaml
  - kafka-node-pool-broker.yaml
  - kafka-node-pool-controller.yaml
  - kafka-topic.yaml

labels:
  - pairs:
      app.kubernetes.io/name: fhir
      managed-by: kustomize
    includeSelectors: true

